name: Trigger Build Qa
on:
  push:
    branches:
      - qa
jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger build workflow in fabric-builder-portainer qa branch
        run: |
          curl -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: token ${{ secrets.GHCR_TOKEN }}" \
            -d '{"ref":"qa"}' \
            https://api.github.com/repos/InnogenioSolutions/fabric-builder-portainer/actions/workflows/build.yaml/dispatches
      